//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.17 at 03:40:53 PM CET 
//


package it.senape.wldiag.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * Corresponds to AuthenticatorMBean
 *  (Interface=weblogic.management.security.authentication.AuthenticatorMBean)
 * 
 * <p>Java class for authenticatorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="authenticatorType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://xmlns.oracle.com/weblogic/security}authentication-providerType">
 *       &lt;sequence>
 *         &lt;element name="control-flag" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="REQUIRED"/>
 *               &lt;enumeration value="REQUISITE"/>
 *               &lt;enumeration value="SUFFICIENT"/>
 *               &lt;enumeration value="OPTIONAL"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "authenticatorType", namespace = "http://xmlns.oracle.com/weblogic/security", propOrder = {
    "controlFlag"
})
public class AuthenticatorType
    extends AuthenticationProviderType
{

    @XmlElementRef(name = "control-flag", namespace = "http://xmlns.oracle.com/weblogic/security", type = JAXBElement.class, required = false)
    protected JAXBElement<String> controlFlag;

    /**
     * Gets the value of the controlFlag property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getControlFlag() {
        return controlFlag;
    }

    /**
     * Sets the value of the controlFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setControlFlag(JAXBElement<String> value) {
        this.controlFlag = value;
    }

}
