//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.17 at 03:40:53 PM CET 
//


package it.senape.wldiag.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Corresponds to CredentialCacheMBean
 *  (Interface=weblogic.management.security.credentials.CredentialCacheMBean)
 * 
 * <p>Java class for credential-cacheType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="credential-cacheType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="credential-caching-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="credentials-cache-size" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="credential-cache-ttl" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "credential-cacheType", namespace = "http://xmlns.oracle.com/weblogic/security", propOrder = {
    "credentialCachingEnabled",
    "credentialsCacheSize",
    "credentialCacheTtl"
})
public class CredentialCacheType {

    @XmlElement(name = "credential-caching-enabled", defaultValue = "false")
    protected Boolean credentialCachingEnabled;
    @XmlElement(name = "credentials-cache-size", defaultValue = "100")
    protected Integer credentialsCacheSize;
    @XmlElement(name = "credential-cache-ttl", defaultValue = "600")
    protected Integer credentialCacheTtl;

    /**
     * Gets the value of the credentialCachingEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCredentialCachingEnabled() {
        return credentialCachingEnabled;
    }

    /**
     * Sets the value of the credentialCachingEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCredentialCachingEnabled(Boolean value) {
        this.credentialCachingEnabled = value;
    }

    /**
     * Gets the value of the credentialsCacheSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCredentialsCacheSize() {
        return credentialsCacheSize;
    }

    /**
     * Sets the value of the credentialsCacheSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCredentialsCacheSize(Integer value) {
        this.credentialsCacheSize = value;
    }

    /**
     * Gets the value of the credentialCacheTtl property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCredentialCacheTtl() {
        return credentialCacheTtl;
    }

    /**
     * Sets the value of the credentialCacheTtl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCredentialCacheTtl(Integer value) {
        this.credentialCacheTtl = value;
    }

}
