//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.17 at 03:40:53 PM CET 
//


package it.senape.wldiag.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Corresponds to DeploymentConfigurationMBean
 *  (Interface=weblogic.management.configuration.DeploymentConfigurationMBean)
 * 
 * <p>Java class for deployment-configurationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="deployment-configurationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://xmlns.oracle.com/weblogic/domain}configurationType">
 *       &lt;sequence>
 *         &lt;element name="max-app-versions" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="65534"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="remote-deployer-ejb-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="restage-only-on-redeploy" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deployment-configurationType", propOrder = {
    "maxAppVersions",
    "remoteDeployerEjbEnabled",
    "restageOnlyOnRedeploy"
})
public class DeploymentConfigurationType
    extends ConfigurationType
{

    @XmlElement(name = "max-app-versions", defaultValue = "2")
    protected Integer maxAppVersions;
    @XmlElement(name = "remote-deployer-ejb-enabled", defaultValue = "false")
    protected Boolean remoteDeployerEjbEnabled;
    @XmlElement(name = "restage-only-on-redeploy", defaultValue = "false")
    protected Boolean restageOnlyOnRedeploy;

    /**
     * Gets the value of the maxAppVersions property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxAppVersions() {
        return maxAppVersions;
    }

    /**
     * Sets the value of the maxAppVersions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxAppVersions(Integer value) {
        this.maxAppVersions = value;
    }

    /**
     * Gets the value of the remoteDeployerEjbEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRemoteDeployerEjbEnabled() {
        return remoteDeployerEjbEnabled;
    }

    /**
     * Sets the value of the remoteDeployerEjbEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRemoteDeployerEjbEnabled(Boolean value) {
        this.remoteDeployerEjbEnabled = value;
    }

    /**
     * Gets the value of the restageOnlyOnRedeploy property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRestageOnlyOnRedeploy() {
        return restageOnlyOnRedeploy;
    }

    /**
     * Sets the value of the restageOnlyOnRedeploy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRestageOnlyOnRedeploy(Boolean value) {
        this.restageOnlyOnRedeploy = value;
    }

}
