//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.17 at 03:40:53 PM CET 
//


package it.senape.wldiag.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Corresponds to DeployableCredentialMapperMBean
 *  (Interface=weblogic.management.security.credentials.DeployableCredentialMapperMBean)
 * 
 * <p>Java class for deployable-credential-mapperType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="deployable-credential-mapperType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://xmlns.oracle.com/weblogic/security}credential-mapperType">
 *       &lt;sequence>
 *         &lt;element name="credential-mapping-deployment-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deployable-credential-mapperType", namespace = "http://xmlns.oracle.com/weblogic/security", propOrder = {
    "credentialMappingDeploymentEnabled"
})
public class DeployableCredentialMapperType
    extends CredentialMapperType
{

    @XmlElement(name = "credential-mapping-deployment-enabled", defaultValue = "true")
    protected Boolean credentialMappingDeploymentEnabled;

    /**
     * Gets the value of the credentialMappingDeploymentEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCredentialMappingDeploymentEnabled() {
        return credentialMappingDeploymentEnabled;
    }

    /**
     * Sets the value of the credentialMappingDeploymentEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCredentialMappingDeploymentEnabled(Boolean value) {
        this.credentialMappingDeploymentEnabled = value;
    }

}
