//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.17 at 03:40:53 PM CET 
//


package it.senape.wldiag.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Corresponds to DeploymentMBean
 *  (Interface=weblogic.management.configuration.DeploymentMBean)
 * 
 * <p>Java class for deploymentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="deploymentType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://xmlns.oracle.com/weblogic/domain}configurationType">
 *       &lt;sequence>
 *         &lt;element name="target" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="deployment-order" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deploymentType", propOrder = {
    "target",
    "deploymentOrder"
})
@XmlSeeAlso({
    JoltConnectionPoolType.class,
    WlecConnectionPoolType.class,
    JdbcTxDataSourceType.class,
    JdbcConnectionPoolType.class,
    MaxThreadsConstraintType.class,
    PersistentStoreType.class,
    MigratableRmiServiceType.class,
    CapacityType.class,
    WtcServerType.class,
    JmsServerType.class,
    FairShareRequestClassType.class,
    RmcFactoryType.class,
    JmsConnectionFactoryType.class,
    WorkManagerType.class,
    CacheType.class,
    FileT3Type.class,
    JdbcDataSourceType.class,
    PathServiceType.class,
    MessagingBridgeType.class,
    VirtualDestinationType.class,
    HttpProxyType.class,
    ContextRequestClassType.class,
    ClassDeploymentType.class,
    NetworkChannelType.class,
    ResponseTimeRequestClassType.class,
    ForeignJmsServerType.class,
    ForeignJndiProviderType.class,
    WebServerType.class,
    ConversationServiceType.class,
    WebDeploymentType.class,
    MinThreadsConstraintType.class,
    SafAgentType.class,
    ComponentType.class,
    JdbcMultiPoolType.class,
    JmsVirtualDestinationType.class,
    ContextCaseType.class
})
public class DeploymentType
    extends ConfigurationType
{

    @XmlElementRef(name = "target", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> target;
    @XmlElement(name = "deployment-order", defaultValue = "1000")
    protected Integer deploymentOrder;

    /**
     * Gets the value of the target property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTarget(JAXBElement<String> value) {
        this.target = value;
    }

    /**
     * Gets the value of the deploymentOrder property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDeploymentOrder() {
        return deploymentOrder;
    }

    /**
     * Sets the value of the deploymentOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDeploymentOrder(Integer value) {
        this.deploymentOrder = value;
    }

}
