//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.17 at 03:40:53 PM CET 
//


package it.senape.wldiag.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Corresponds to GenericFileStoreMBean
 *  (Interface=weblogic.management.configuration.GenericFileStoreMBean)
 * 
 * <p>Java class for generic-file-storeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="generic-file-storeType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://xmlns.oracle.com/weblogic/domain}configurationType">
 *       &lt;sequence>
 *         &lt;element name="directory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="synchronous-write-policy" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Disabled"/>
 *               &lt;enumeration value="Cache-Flush"/>
 *               &lt;enumeration value="Direct-Write"/>
 *               &lt;enumeration value="Direct-Write-With-Cache"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="cache-directory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="min-window-buffer-size" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="-1"/>
 *               &lt;maxInclusive value="1073741824"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="max-window-buffer-size" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="-1"/>
 *               &lt;maxInclusive value="1073741824"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="io-buffer-size" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="-1"/>
 *               &lt;maxInclusive value="67108864"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="max-file-size" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *               &lt;minInclusive value="1048576"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="block-size" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="512"/>
 *               &lt;maxInclusive value="8192"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="initial-size" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *               &lt;minInclusive value="1048576"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="file-locking-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "generic-file-storeType", propOrder = {
    "directory",
    "synchronousWritePolicy",
    "cacheDirectory",
    "minWindowBufferSize",
    "maxWindowBufferSize",
    "ioBufferSize",
    "maxFileSize",
    "blockSize",
    "initialSize",
    "fileLockingEnabled"
})
@XmlSeeAlso({
    DefaultFileStoreType.class,
    FileStoreType.class
})
public class GenericFileStoreType
    extends ConfigurationType
{

    @XmlElementRef(name = "directory", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> directory;
    @XmlElementRef(name = "synchronous-write-policy", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> synchronousWritePolicy;
    @XmlElementRef(name = "cache-directory", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> cacheDirectory;
    @XmlElement(name = "min-window-buffer-size", defaultValue = "-1")
    protected Integer minWindowBufferSize;
    @XmlElement(name = "max-window-buffer-size", defaultValue = "-1")
    protected Integer maxWindowBufferSize;
    @XmlElement(name = "io-buffer-size", defaultValue = "-1")
    protected Integer ioBufferSize;
    @XmlElement(name = "max-file-size", defaultValue = "1342177280")
    protected Long maxFileSize;
    @XmlElement(name = "block-size", defaultValue = "512")
    protected Integer blockSize;
    @XmlElement(name = "initial-size", defaultValue = "1048576")
    protected Long initialSize;
    @XmlElement(name = "file-locking-enabled", defaultValue = "true")
    protected Boolean fileLockingEnabled;

    /**
     * Gets the value of the directory property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDirectory() {
        return directory;
    }

    /**
     * Sets the value of the directory property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDirectory(JAXBElement<String> value) {
        this.directory = value;
    }

    /**
     * Gets the value of the synchronousWritePolicy property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSynchronousWritePolicy() {
        return synchronousWritePolicy;
    }

    /**
     * Sets the value of the synchronousWritePolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSynchronousWritePolicy(JAXBElement<String> value) {
        this.synchronousWritePolicy = value;
    }

    /**
     * Gets the value of the cacheDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCacheDirectory() {
        return cacheDirectory;
    }

    /**
     * Sets the value of the cacheDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCacheDirectory(JAXBElement<String> value) {
        this.cacheDirectory = value;
    }

    /**
     * Gets the value of the minWindowBufferSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMinWindowBufferSize() {
        return minWindowBufferSize;
    }

    /**
     * Sets the value of the minWindowBufferSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinWindowBufferSize(Integer value) {
        this.minWindowBufferSize = value;
    }

    /**
     * Gets the value of the maxWindowBufferSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxWindowBufferSize() {
        return maxWindowBufferSize;
    }

    /**
     * Sets the value of the maxWindowBufferSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxWindowBufferSize(Integer value) {
        this.maxWindowBufferSize = value;
    }

    /**
     * Gets the value of the ioBufferSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIoBufferSize() {
        return ioBufferSize;
    }

    /**
     * Sets the value of the ioBufferSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIoBufferSize(Integer value) {
        this.ioBufferSize = value;
    }

    /**
     * Gets the value of the maxFileSize property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxFileSize() {
        return maxFileSize;
    }

    /**
     * Sets the value of the maxFileSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxFileSize(Long value) {
        this.maxFileSize = value;
    }

    /**
     * Gets the value of the blockSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBlockSize() {
        return blockSize;
    }

    /**
     * Sets the value of the blockSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBlockSize(Integer value) {
        this.blockSize = value;
    }

    /**
     * Gets the value of the initialSize property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getInitialSize() {
        return initialSize;
    }

    /**
     * Sets the value of the initialSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setInitialSize(Long value) {
        this.initialSize = value;
    }

    /**
     * Gets the value of the fileLockingEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFileLockingEnabled() {
        return fileLockingEnabled;
    }

    /**
     * Sets the value of the fileLockingEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFileLockingEnabled(Boolean value) {
        this.fileLockingEnabled = value;
    }

}
