//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.17 at 03:40:53 PM CET 
//


package it.senape.wldiag.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * Corresponds to IdentityDomainAuthenticatorMBean
 *  (Interface=weblogic.management.security.authentication.IdentityDomainAuthenticatorMBean)
 * 
 * <p>Java class for identity-domain-authenticatorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="identity-domain-authenticatorType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://xmlns.oracle.com/weblogic/security}identity-domain-aware-providerType">
 *       &lt;sequence>
 *         &lt;element name="identity-domain" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "identity-domain-authenticatorType", namespace = "http://xmlns.oracle.com/weblogic/security", propOrder = {
    "identityDomain"
})
public class IdentityDomainAuthenticatorType
    extends IdentityDomainAwareProviderType
{

    @XmlElementRef(name = "identity-domain", namespace = "http://xmlns.oracle.com/weblogic/security", type = JAXBElement.class, required = false)
    protected JAXBElement<String> identityDomain;

    /**
     * Gets the value of the identityDomain property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getIdentityDomain() {
        return identityDomain;
    }

    /**
     * Sets the value of the identityDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setIdentityDomain(JAXBElement<String> value) {
        this.identityDomain = value;
    }

}
