//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.17 at 03:40:53 PM CET 
//


package it.senape.wldiag.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Corresponds to JTAMigratableTargetMBean
 *  (Interface=weblogic.management.configuration.JTAMigratableTargetMBean)
 * 
 * <p>Java class for jta-migratable-targetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="jta-migratable-targetType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://xmlns.oracle.com/weblogic/domain}migratable-targetType">
 *       &lt;sequence>
 *         &lt;element name="strict-ownership-check" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "jta-migratable-targetType", propOrder = {
    "strictOwnershipCheck"
})
public class JtaMigratableTargetType
    extends MigratableTargetType
{

    @XmlElement(name = "strict-ownership-check", defaultValue = "false")
    protected Boolean strictOwnershipCheck;

    /**
     * Gets the value of the strictOwnershipCheck property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isStrictOwnershipCheck() {
        return strictOwnershipCheck;
    }

    /**
     * Sets the value of the strictOwnershipCheck property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStrictOwnershipCheck(Boolean value) {
        this.strictOwnershipCheck = value;
    }

}
