//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.17 at 03:40:53 PM CET 
//


package it.senape.wldiag.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * Corresponds to LDAPServerMBean
 *  (Interface=weblogic.management.utils.LDAPServerMBean)
 * 
 * <p>Java class for ldap-serverType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ldap-serverType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="host" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="port" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="65534"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ssl-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="principal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="credential-encrypted" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cache-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="cache-size" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="cache-ttl" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="follow-referrals" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="bind-anonymously-on-referrals" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="results-time-limit" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="connect-timeout" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="parallel-connect-delay" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="connection-retry-limit" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="connection-pool-size" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ldap-serverType", namespace = "http://xmlns.oracle.com/weblogic/security", propOrder = {
    "host",
    "port",
    "sslEnabled",
    "principal",
    "credentialEncrypted",
    "cacheEnabled",
    "cacheSize",
    "cacheTtl",
    "followReferrals",
    "bindAnonymouslyOnReferrals",
    "resultsTimeLimit",
    "connectTimeout",
    "parallelConnectDelay",
    "connectionRetryLimit",
    "connectionPoolSize"
})
public class LdapServerType {

    @XmlElementRef(name = "host", namespace = "http://xmlns.oracle.com/weblogic/security", type = JAXBElement.class, required = false)
    protected JAXBElement<String> host;
    @XmlElement(defaultValue = "389")
    protected Integer port;
    @XmlElement(name = "ssl-enabled", defaultValue = "false")
    protected Boolean sslEnabled;
    @XmlElementRef(name = "principal", namespace = "http://xmlns.oracle.com/weblogic/security", type = JAXBElement.class, required = false)
    protected JAXBElement<String> principal;
    @XmlElementRef(name = "credential-encrypted", namespace = "http://xmlns.oracle.com/weblogic/security", type = JAXBElement.class, required = false)
    protected JAXBElement<String> credentialEncrypted;
    @XmlElement(name = "cache-enabled", defaultValue = "true")
    protected Boolean cacheEnabled;
    @XmlElement(name = "cache-size", defaultValue = "32")
    protected Integer cacheSize;
    @XmlElement(name = "cache-ttl", defaultValue = "60")
    protected Integer cacheTtl;
    @XmlElement(name = "follow-referrals", defaultValue = "true")
    protected Boolean followReferrals;
    @XmlElement(name = "bind-anonymously-on-referrals", defaultValue = "false")
    protected Boolean bindAnonymouslyOnReferrals;
    @XmlElement(name = "results-time-limit", defaultValue = "0")
    protected Integer resultsTimeLimit;
    @XmlElement(name = "connect-timeout", defaultValue = "0")
    protected Integer connectTimeout;
    @XmlElement(name = "parallel-connect-delay", defaultValue = "0")
    protected Integer parallelConnectDelay;
    @XmlElement(name = "connection-retry-limit", defaultValue = "1")
    protected Integer connectionRetryLimit;
    @XmlElement(name = "connection-pool-size", defaultValue = "6")
    protected Integer connectionPoolSize;

    /**
     * Gets the value of the host property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getHost() {
        return host;
    }

    /**
     * Sets the value of the host property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setHost(JAXBElement<String> value) {
        this.host = value;
    }

    /**
     * Gets the value of the port property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPort(Integer value) {
        this.port = value;
    }

    /**
     * Gets the value of the sslEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSslEnabled() {
        return sslEnabled;
    }

    /**
     * Sets the value of the sslEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSslEnabled(Boolean value) {
        this.sslEnabled = value;
    }

    /**
     * Gets the value of the principal property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPrincipal() {
        return principal;
    }

    /**
     * Sets the value of the principal property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPrincipal(JAXBElement<String> value) {
        this.principal = value;
    }

    /**
     * Gets the value of the credentialEncrypted property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCredentialEncrypted() {
        return credentialEncrypted;
    }

    /**
     * Sets the value of the credentialEncrypted property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCredentialEncrypted(JAXBElement<String> value) {
        this.credentialEncrypted = value;
    }

    /**
     * Gets the value of the cacheEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCacheEnabled() {
        return cacheEnabled;
    }

    /**
     * Sets the value of the cacheEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCacheEnabled(Boolean value) {
        this.cacheEnabled = value;
    }

    /**
     * Gets the value of the cacheSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCacheSize() {
        return cacheSize;
    }

    /**
     * Sets the value of the cacheSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCacheSize(Integer value) {
        this.cacheSize = value;
    }

    /**
     * Gets the value of the cacheTtl property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCacheTtl() {
        return cacheTtl;
    }

    /**
     * Sets the value of the cacheTtl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCacheTtl(Integer value) {
        this.cacheTtl = value;
    }

    /**
     * Gets the value of the followReferrals property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFollowReferrals() {
        return followReferrals;
    }

    /**
     * Sets the value of the followReferrals property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFollowReferrals(Boolean value) {
        this.followReferrals = value;
    }

    /**
     * Gets the value of the bindAnonymouslyOnReferrals property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBindAnonymouslyOnReferrals() {
        return bindAnonymouslyOnReferrals;
    }

    /**
     * Sets the value of the bindAnonymouslyOnReferrals property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBindAnonymouslyOnReferrals(Boolean value) {
        this.bindAnonymouslyOnReferrals = value;
    }

    /**
     * Gets the value of the resultsTimeLimit property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getResultsTimeLimit() {
        return resultsTimeLimit;
    }

    /**
     * Sets the value of the resultsTimeLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setResultsTimeLimit(Integer value) {
        this.resultsTimeLimit = value;
    }

    /**
     * Gets the value of the connectTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getConnectTimeout() {
        return connectTimeout;
    }

    /**
     * Sets the value of the connectTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setConnectTimeout(Integer value) {
        this.connectTimeout = value;
    }

    /**
     * Gets the value of the parallelConnectDelay property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getParallelConnectDelay() {
        return parallelConnectDelay;
    }

    /**
     * Sets the value of the parallelConnectDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setParallelConnectDelay(Integer value) {
        this.parallelConnectDelay = value;
    }

    /**
     * Gets the value of the connectionRetryLimit property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getConnectionRetryLimit() {
        return connectionRetryLimit;
    }

    /**
     * Sets the value of the connectionRetryLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setConnectionRetryLimit(Integer value) {
        this.connectionRetryLimit = value;
    }

    /**
     * Gets the value of the connectionPoolSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getConnectionPoolSize() {
        return connectionPoolSize;
    }

    /**
     * Sets the value of the connectionPoolSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setConnectionPoolSize(Integer value) {
        this.connectionPoolSize = value;
    }

}
