//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.17 at 03:40:53 PM CET 
//


package it.senape.wldiag.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * Corresponds to NetworkChannelMBean
 *  (Interface=weblogic.management.configuration.NetworkChannelMBean)
 * 
 * <p>Java class for network-channelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="network-channelType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://xmlns.oracle.com/weblogic/domain}deploymentType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="listen-port" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="65535"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="listen-port-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ssl-listen-port" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="65535"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ssl-listen-port-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="cluster-address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="t3-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="t3s-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="http-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="https-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="com-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="outgoing-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="bound-outgoing-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="channel-weight" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="accept-backlog" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="login-timeout-millis" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="100000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="login-timeout-millis-ssl" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tunneling-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="tunneling-client-ping-secs" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tunneling-client-timeout-secs" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="complete-t3-message-timeout" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="480"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="complete-http-message-timeout" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="480"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="complete-com-message-timeout" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="480"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="max-t3-message-size" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="4096"/>
 *               &lt;maxInclusive value="2000000000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="max-http-message-size" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="4096"/>
 *               &lt;maxInclusive value="2000000000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="max-com-message-size" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="4096"/>
 *               &lt;maxInclusive value="2000000000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="iiop-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="iiops-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="complete-iiop-message-timeout" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="480"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="max-iiop-message-size" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="4096"/>
 *               &lt;maxInclusive value="2000000000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="idle-iiop-connection-timeout" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="default-iiop-user" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="default-iiop-password-encrypted" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "network-channelType", propOrder = {
    "description",
    "listenPort",
    "listenPortEnabled",
    "sslListenPort",
    "sslListenPortEnabled",
    "clusterAddress",
    "t3Enabled",
    "t3SEnabled",
    "httpEnabled",
    "httpsEnabled",
    "comEnabled",
    "outgoingEnabled",
    "boundOutgoingEnabled",
    "channelWeight",
    "acceptBacklog",
    "loginTimeoutMillis",
    "loginTimeoutMillisSsl",
    "tunnelingEnabled",
    "tunnelingClientPingSecs",
    "tunnelingClientTimeoutSecs",
    "completeT3MessageTimeout",
    "completeHttpMessageTimeout",
    "completeComMessageTimeout",
    "maxT3MessageSize",
    "maxHttpMessageSize",
    "maxComMessageSize",
    "iiopEnabled",
    "iiopsEnabled",
    "completeIiopMessageTimeout",
    "maxIiopMessageSize",
    "idleIiopConnectionTimeout",
    "defaultIiopUser",
    "defaultIiopPasswordEncrypted"
})
public class NetworkChannelType
    extends DeploymentType
{

    @XmlElementRef(name = "description", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> description;
    @XmlElement(name = "listen-port", defaultValue = "8001")
    protected Integer listenPort;
    @XmlElement(name = "listen-port-enabled", defaultValue = "false")
    protected Boolean listenPortEnabled;
    @XmlElement(name = "ssl-listen-port", defaultValue = "8002")
    protected Integer sslListenPort;
    @XmlElement(name = "ssl-listen-port-enabled", defaultValue = "false")
    protected Boolean sslListenPortEnabled;
    @XmlElementRef(name = "cluster-address", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> clusterAddress;
    @XmlElement(name = "t3-enabled", defaultValue = "false")
    protected Boolean t3Enabled;
    @XmlElement(name = "t3s-enabled", defaultValue = "false")
    protected Boolean t3SEnabled;
    @XmlElement(name = "http-enabled", defaultValue = "false")
    protected Boolean httpEnabled;
    @XmlElement(name = "https-enabled", defaultValue = "false")
    protected Boolean httpsEnabled;
    @XmlElement(name = "com-enabled", defaultValue = "false")
    protected Boolean comEnabled;
    @XmlElement(name = "outgoing-enabled", defaultValue = "false")
    protected Boolean outgoingEnabled;
    @XmlElement(name = "bound-outgoing-enabled", defaultValue = "false")
    protected Boolean boundOutgoingEnabled;
    @XmlElement(name = "channel-weight", defaultValue = "50")
    protected Integer channelWeight;
    @XmlElement(name = "accept-backlog", defaultValue = "50")
    protected Integer acceptBacklog;
    @XmlElement(name = "login-timeout-millis", defaultValue = "5000")
    protected Integer loginTimeoutMillis;
    @XmlElement(name = "login-timeout-millis-ssl", defaultValue = "25000")
    protected Integer loginTimeoutMillisSsl;
    @XmlElement(name = "tunneling-enabled", defaultValue = "false")
    protected Boolean tunnelingEnabled;
    @XmlElement(name = "tunneling-client-ping-secs", defaultValue = "45")
    protected Integer tunnelingClientPingSecs;
    @XmlElement(name = "tunneling-client-timeout-secs", defaultValue = "40")
    protected Integer tunnelingClientTimeoutSecs;
    @XmlElement(name = "complete-t3-message-timeout", defaultValue = "60")
    protected Integer completeT3MessageTimeout;
    @XmlElement(name = "complete-http-message-timeout", defaultValue = "60")
    protected Integer completeHttpMessageTimeout;
    @XmlElement(name = "complete-com-message-timeout", defaultValue = "60")
    protected Integer completeComMessageTimeout;
    @XmlElement(name = "max-t3-message-size", defaultValue = "10000000")
    protected Integer maxT3MessageSize;
    @XmlElement(name = "max-http-message-size", defaultValue = "10000000")
    protected Integer maxHttpMessageSize;
    @XmlElement(name = "max-com-message-size", defaultValue = "10000000")
    protected Integer maxComMessageSize;
    @XmlElement(name = "iiop-enabled", defaultValue = "false")
    protected Boolean iiopEnabled;
    @XmlElement(name = "iiops-enabled", defaultValue = "false")
    protected Boolean iiopsEnabled;
    @XmlElement(name = "complete-iiop-message-timeout", defaultValue = "60")
    protected Integer completeIiopMessageTimeout;
    @XmlElement(name = "max-iiop-message-size", defaultValue = "10000000")
    protected Integer maxIiopMessageSize;
    @XmlElement(name = "idle-iiop-connection-timeout", defaultValue = "60")
    protected Integer idleIiopConnectionTimeout;
    @XmlElementRef(name = "default-iiop-user", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> defaultIiopUser;
    @XmlElementRef(name = "default-iiop-password-encrypted", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> defaultIiopPasswordEncrypted;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDescription(JAXBElement<String> value) {
        this.description = value;
    }

    /**
     * Gets the value of the listenPort property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getListenPort() {
        return listenPort;
    }

    /**
     * Sets the value of the listenPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setListenPort(Integer value) {
        this.listenPort = value;
    }

    /**
     * Gets the value of the listenPortEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isListenPortEnabled() {
        return listenPortEnabled;
    }

    /**
     * Sets the value of the listenPortEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setListenPortEnabled(Boolean value) {
        this.listenPortEnabled = value;
    }

    /**
     * Gets the value of the sslListenPort property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSslListenPort() {
        return sslListenPort;
    }

    /**
     * Sets the value of the sslListenPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSslListenPort(Integer value) {
        this.sslListenPort = value;
    }

    /**
     * Gets the value of the sslListenPortEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSslListenPortEnabled() {
        return sslListenPortEnabled;
    }

    /**
     * Sets the value of the sslListenPortEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSslListenPortEnabled(Boolean value) {
        this.sslListenPortEnabled = value;
    }

    /**
     * Gets the value of the clusterAddress property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getClusterAddress() {
        return clusterAddress;
    }

    /**
     * Sets the value of the clusterAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setClusterAddress(JAXBElement<String> value) {
        this.clusterAddress = value;
    }

    /**
     * Gets the value of the t3Enabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isT3Enabled() {
        return t3Enabled;
    }

    /**
     * Sets the value of the t3Enabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setT3Enabled(Boolean value) {
        this.t3Enabled = value;
    }

    /**
     * Gets the value of the t3SEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isT3SEnabled() {
        return t3SEnabled;
    }

    /**
     * Sets the value of the t3SEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setT3SEnabled(Boolean value) {
        this.t3SEnabled = value;
    }

    /**
     * Gets the value of the httpEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHttpEnabled() {
        return httpEnabled;
    }

    /**
     * Sets the value of the httpEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHttpEnabled(Boolean value) {
        this.httpEnabled = value;
    }

    /**
     * Gets the value of the httpsEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHttpsEnabled() {
        return httpsEnabled;
    }

    /**
     * Sets the value of the httpsEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHttpsEnabled(Boolean value) {
        this.httpsEnabled = value;
    }

    /**
     * Gets the value of the comEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isComEnabled() {
        return comEnabled;
    }

    /**
     * Sets the value of the comEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setComEnabled(Boolean value) {
        this.comEnabled = value;
    }

    /**
     * Gets the value of the outgoingEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOutgoingEnabled() {
        return outgoingEnabled;
    }

    /**
     * Sets the value of the outgoingEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOutgoingEnabled(Boolean value) {
        this.outgoingEnabled = value;
    }

    /**
     * Gets the value of the boundOutgoingEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBoundOutgoingEnabled() {
        return boundOutgoingEnabled;
    }

    /**
     * Sets the value of the boundOutgoingEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBoundOutgoingEnabled(Boolean value) {
        this.boundOutgoingEnabled = value;
    }

    /**
     * Gets the value of the channelWeight property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getChannelWeight() {
        return channelWeight;
    }

    /**
     * Sets the value of the channelWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setChannelWeight(Integer value) {
        this.channelWeight = value;
    }

    /**
     * Gets the value of the acceptBacklog property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAcceptBacklog() {
        return acceptBacklog;
    }

    /**
     * Sets the value of the acceptBacklog property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAcceptBacklog(Integer value) {
        this.acceptBacklog = value;
    }

    /**
     * Gets the value of the loginTimeoutMillis property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLoginTimeoutMillis() {
        return loginTimeoutMillis;
    }

    /**
     * Sets the value of the loginTimeoutMillis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLoginTimeoutMillis(Integer value) {
        this.loginTimeoutMillis = value;
    }

    /**
     * Gets the value of the loginTimeoutMillisSsl property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLoginTimeoutMillisSsl() {
        return loginTimeoutMillisSsl;
    }

    /**
     * Sets the value of the loginTimeoutMillisSsl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLoginTimeoutMillisSsl(Integer value) {
        this.loginTimeoutMillisSsl = value;
    }

    /**
     * Gets the value of the tunnelingEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTunnelingEnabled() {
        return tunnelingEnabled;
    }

    /**
     * Sets the value of the tunnelingEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTunnelingEnabled(Boolean value) {
        this.tunnelingEnabled = value;
    }

    /**
     * Gets the value of the tunnelingClientPingSecs property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTunnelingClientPingSecs() {
        return tunnelingClientPingSecs;
    }

    /**
     * Sets the value of the tunnelingClientPingSecs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTunnelingClientPingSecs(Integer value) {
        this.tunnelingClientPingSecs = value;
    }

    /**
     * Gets the value of the tunnelingClientTimeoutSecs property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTunnelingClientTimeoutSecs() {
        return tunnelingClientTimeoutSecs;
    }

    /**
     * Sets the value of the tunnelingClientTimeoutSecs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTunnelingClientTimeoutSecs(Integer value) {
        this.tunnelingClientTimeoutSecs = value;
    }

    /**
     * Gets the value of the completeT3MessageTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCompleteT3MessageTimeout() {
        return completeT3MessageTimeout;
    }

    /**
     * Sets the value of the completeT3MessageTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCompleteT3MessageTimeout(Integer value) {
        this.completeT3MessageTimeout = value;
    }

    /**
     * Gets the value of the completeHttpMessageTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCompleteHttpMessageTimeout() {
        return completeHttpMessageTimeout;
    }

    /**
     * Sets the value of the completeHttpMessageTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCompleteHttpMessageTimeout(Integer value) {
        this.completeHttpMessageTimeout = value;
    }

    /**
     * Gets the value of the completeComMessageTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCompleteComMessageTimeout() {
        return completeComMessageTimeout;
    }

    /**
     * Sets the value of the completeComMessageTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCompleteComMessageTimeout(Integer value) {
        this.completeComMessageTimeout = value;
    }

    /**
     * Gets the value of the maxT3MessageSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxT3MessageSize() {
        return maxT3MessageSize;
    }

    /**
     * Sets the value of the maxT3MessageSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxT3MessageSize(Integer value) {
        this.maxT3MessageSize = value;
    }

    /**
     * Gets the value of the maxHttpMessageSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxHttpMessageSize() {
        return maxHttpMessageSize;
    }

    /**
     * Sets the value of the maxHttpMessageSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxHttpMessageSize(Integer value) {
        this.maxHttpMessageSize = value;
    }

    /**
     * Gets the value of the maxComMessageSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxComMessageSize() {
        return maxComMessageSize;
    }

    /**
     * Sets the value of the maxComMessageSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxComMessageSize(Integer value) {
        this.maxComMessageSize = value;
    }

    /**
     * Gets the value of the iiopEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIiopEnabled() {
        return iiopEnabled;
    }

    /**
     * Sets the value of the iiopEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIiopEnabled(Boolean value) {
        this.iiopEnabled = value;
    }

    /**
     * Gets the value of the iiopsEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIiopsEnabled() {
        return iiopsEnabled;
    }

    /**
     * Sets the value of the iiopsEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIiopsEnabled(Boolean value) {
        this.iiopsEnabled = value;
    }

    /**
     * Gets the value of the completeIiopMessageTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCompleteIiopMessageTimeout() {
        return completeIiopMessageTimeout;
    }

    /**
     * Sets the value of the completeIiopMessageTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCompleteIiopMessageTimeout(Integer value) {
        this.completeIiopMessageTimeout = value;
    }

    /**
     * Gets the value of the maxIiopMessageSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxIiopMessageSize() {
        return maxIiopMessageSize;
    }

    /**
     * Sets the value of the maxIiopMessageSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxIiopMessageSize(Integer value) {
        this.maxIiopMessageSize = value;
    }

    /**
     * Gets the value of the idleIiopConnectionTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdleIiopConnectionTimeout() {
        return idleIiopConnectionTimeout;
    }

    /**
     * Sets the value of the idleIiopConnectionTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdleIiopConnectionTimeout(Integer value) {
        this.idleIiopConnectionTimeout = value;
    }

    /**
     * Gets the value of the defaultIiopUser property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDefaultIiopUser() {
        return defaultIiopUser;
    }

    /**
     * Sets the value of the defaultIiopUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDefaultIiopUser(JAXBElement<String> value) {
        this.defaultIiopUser = value;
    }

    /**
     * Gets the value of the defaultIiopPasswordEncrypted property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDefaultIiopPasswordEncrypted() {
        return defaultIiopPasswordEncrypted;
    }

    /**
     * Sets the value of the defaultIiopPasswordEncrypted property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDefaultIiopPasswordEncrypted(JAXBElement<String> value) {
        this.defaultIiopPasswordEncrypted = value;
    }

}
