//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.17 at 03:40:53 PM CET 
//


package it.senape.wldiag.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * Corresponds to OverloadProtectionMBean
 *  (Interface=weblogic.management.configuration.OverloadProtectionMBean)
 * 
 * <p>Java class for overload-protectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="overload-protectionType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://xmlns.oracle.com/weblogic/domain}configurationType">
 *       &lt;sequence>
 *         &lt;element name="shared-capacity-for-work-managers" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="1073741824"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="panic-action" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="no-action"/>
 *               &lt;enumeration value="system-exit"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="failure-action" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="no-action"/>
 *               &lt;enumeration value="force-shutdown"/>
 *               &lt;enumeration value="admin-state"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="free-memory-percent-high-threshold" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="99"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="free-memory-percent-low-threshold" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="99"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="server-failure-trigger" type="{http://xmlns.oracle.com/weblogic/domain}server-failure-triggerType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "overload-protectionType", propOrder = {
    "sharedCapacityForWorkManagers",
    "panicAction",
    "failureAction",
    "freeMemoryPercentHighThreshold",
    "freeMemoryPercentLowThreshold",
    "serverFailureTrigger"
})
public class OverloadProtectionType
    extends ConfigurationType
{

    @XmlElement(name = "shared-capacity-for-work-managers", defaultValue = "65536")
    protected Integer sharedCapacityForWorkManagers;
    @XmlElementRef(name = "panic-action", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> panicAction;
    @XmlElementRef(name = "failure-action", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> failureAction;
    @XmlElement(name = "free-memory-percent-high-threshold", defaultValue = "0")
    protected Integer freeMemoryPercentHighThreshold;
    @XmlElement(name = "free-memory-percent-low-threshold", defaultValue = "0")
    protected Integer freeMemoryPercentLowThreshold;
    @XmlElementRef(name = "server-failure-trigger", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<ServerFailureTriggerType> serverFailureTrigger;

    /**
     * Gets the value of the sharedCapacityForWorkManagers property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSharedCapacityForWorkManagers() {
        return sharedCapacityForWorkManagers;
    }

    /**
     * Sets the value of the sharedCapacityForWorkManagers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSharedCapacityForWorkManagers(Integer value) {
        this.sharedCapacityForWorkManagers = value;
    }

    /**
     * Gets the value of the panicAction property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPanicAction() {
        return panicAction;
    }

    /**
     * Sets the value of the panicAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPanicAction(JAXBElement<String> value) {
        this.panicAction = value;
    }

    /**
     * Gets the value of the failureAction property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getFailureAction() {
        return failureAction;
    }

    /**
     * Sets the value of the failureAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setFailureAction(JAXBElement<String> value) {
        this.failureAction = value;
    }

    /**
     * Gets the value of the freeMemoryPercentHighThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFreeMemoryPercentHighThreshold() {
        return freeMemoryPercentHighThreshold;
    }

    /**
     * Sets the value of the freeMemoryPercentHighThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFreeMemoryPercentHighThreshold(Integer value) {
        this.freeMemoryPercentHighThreshold = value;
    }

    /**
     * Gets the value of the freeMemoryPercentLowThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFreeMemoryPercentLowThreshold() {
        return freeMemoryPercentLowThreshold;
    }

    /**
     * Sets the value of the freeMemoryPercentLowThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFreeMemoryPercentLowThreshold(Integer value) {
        this.freeMemoryPercentLowThreshold = value;
    }

    /**
     * Gets the value of the serverFailureTrigger property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ServerFailureTriggerType }{@code >}
     *     
     */
    public JAXBElement<ServerFailureTriggerType> getServerFailureTrigger() {
        return serverFailureTrigger;
    }

    /**
     * Sets the value of the serverFailureTrigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ServerFailureTriggerType }{@code >}
     *     
     */
    public void setServerFailureTrigger(JAXBElement<ServerFailureTriggerType> value) {
        this.serverFailureTrigger = value;
    }

}
