//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.17 at 03:40:53 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xmlns.oracle.com/weblogic/domain", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.senape.wldiag.xml;
