//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.17 at 03:40:53 PM CET 
//


package it.senape.wldiag.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Corresponds to PasswordPolicyMBean
 *  (Interface=weblogic.management.configuration.PasswordPolicyMBean)
 * 
 * <p>Java class for password-policyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="password-policyType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://xmlns.oracle.com/weblogic/domain}configurationType">
 *       &lt;sequence>
 *         &lt;element name="minimum-password-length" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="lockout-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="lockout-threshold" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="99999"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="lockout-duration" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="999999"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="lockout-reset-duration" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="99999"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="lockout-cache-size" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="99999"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="lockout-gc-threshold" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="999999"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "password-policyType", propOrder = {
    "minimumPasswordLength",
    "lockoutEnabled",
    "lockoutThreshold",
    "lockoutDuration",
    "lockoutResetDuration",
    "lockoutCacheSize",
    "lockoutGcThreshold"
})
public class PasswordPolicyType
    extends ConfigurationType
{

    @XmlElement(name = "minimum-password-length", defaultValue = "8")
    protected Integer minimumPasswordLength;
    @XmlElement(name = "lockout-enabled", defaultValue = "true")
    protected Boolean lockoutEnabled;
    @XmlElement(name = "lockout-threshold", defaultValue = "5")
    protected Integer lockoutThreshold;
    @XmlElement(name = "lockout-duration", defaultValue = "30")
    protected Integer lockoutDuration;
    @XmlElement(name = "lockout-reset-duration", defaultValue = "5")
    protected Integer lockoutResetDuration;
    @XmlElement(name = "lockout-cache-size", defaultValue = "5")
    protected Integer lockoutCacheSize;
    @XmlElement(name = "lockout-gc-threshold", defaultValue = "400")
    protected Integer lockoutGcThreshold;

    /**
     * Gets the value of the minimumPasswordLength property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMinimumPasswordLength() {
        return minimumPasswordLength;
    }

    /**
     * Sets the value of the minimumPasswordLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinimumPasswordLength(Integer value) {
        this.minimumPasswordLength = value;
    }

    /**
     * Gets the value of the lockoutEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLockoutEnabled() {
        return lockoutEnabled;
    }

    /**
     * Sets the value of the lockoutEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLockoutEnabled(Boolean value) {
        this.lockoutEnabled = value;
    }

    /**
     * Gets the value of the lockoutThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLockoutThreshold() {
        return lockoutThreshold;
    }

    /**
     * Sets the value of the lockoutThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLockoutThreshold(Integer value) {
        this.lockoutThreshold = value;
    }

    /**
     * Gets the value of the lockoutDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLockoutDuration() {
        return lockoutDuration;
    }

    /**
     * Sets the value of the lockoutDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLockoutDuration(Integer value) {
        this.lockoutDuration = value;
    }

    /**
     * Gets the value of the lockoutResetDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLockoutResetDuration() {
        return lockoutResetDuration;
    }

    /**
     * Sets the value of the lockoutResetDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLockoutResetDuration(Integer value) {
        this.lockoutResetDuration = value;
    }

    /**
     * Gets the value of the lockoutCacheSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLockoutCacheSize() {
        return lockoutCacheSize;
    }

    /**
     * Sets the value of the lockoutCacheSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLockoutCacheSize(Integer value) {
        this.lockoutCacheSize = value;
    }

    /**
     * Gets the value of the lockoutGcThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLockoutGcThreshold() {
        return lockoutGcThreshold;
    }

    /**
     * Sets the value of the lockoutGcThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLockoutGcThreshold(Integer value) {
        this.lockoutGcThreshold = value;
    }

}
