//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.17 at 03:40:53 PM CET 
//


package it.senape.wldiag.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Corresponds to PKICredentialMapExtendedReaderMBean
 *  (Interface=weblogic.management.security.credentials.PKICredentialMapExtendedReaderMBean)
 * 
 * <p>Java class for pki-credential-map-extended-readerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pki-credential-map-extended-readerType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://xmlns.oracle.com/weblogic/security}pki-credential-map-readerType">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pki-credential-map-extended-readerType", namespace = "http://xmlns.oracle.com/weblogic/security")
@XmlSeeAlso({
    PkiCredentialMapExtendedEditorType.class
})
public class PkiCredentialMapExtendedReaderType
    extends PkiCredentialMapReaderType
{


}
