//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.17 at 03:40:53 PM CET 
//


package it.senape.wldiag.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Corresponds to SNMPJMXMonitorMBean
 *  (Interface=weblogic.management.configuration.SNMPJMXMonitorMBean)
 * 
 * <p>Java class for snmp-jmx-monitorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="snmp-jmx-monitorType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://xmlns.oracle.com/weblogic/domain}snmp-trap-sourceType">
 *       &lt;sequence>
 *         &lt;element name="monitored-m-bean-type" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="monitored-m-bean-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="monitored-attribute-name" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="polling-interval" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="65535"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "snmp-jmx-monitorType", propOrder = {
    "monitoredMBeanType",
    "monitoredMBeanName",
    "monitoredAttributeName",
    "pollingInterval"
})
@XmlSeeAlso({
    SnmpGaugeMonitorType.class,
    SnmpCounterMonitorType.class,
    SnmpStringMonitorType.class
})
public class SnmpJmxMonitorType
    extends SnmpTrapSourceType
{

    @XmlElementRef(name = "monitored-m-bean-type", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> monitoredMBeanType;
    @XmlElementRef(name = "monitored-m-bean-name", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> monitoredMBeanName;
    @XmlElementRef(name = "monitored-attribute-name", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> monitoredAttributeName;
    @XmlElement(name = "polling-interval", defaultValue = "10")
    protected Integer pollingInterval;

    /**
     * Gets the value of the monitoredMBeanType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getMonitoredMBeanType() {
        return monitoredMBeanType;
    }

    /**
     * Sets the value of the monitoredMBeanType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setMonitoredMBeanType(JAXBElement<String> value) {
        this.monitoredMBeanType = value;
    }

    /**
     * Gets the value of the monitoredMBeanName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getMonitoredMBeanName() {
        return monitoredMBeanName;
    }

    /**
     * Sets the value of the monitoredMBeanName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setMonitoredMBeanName(JAXBElement<String> value) {
        this.monitoredMBeanName = value;
    }

    /**
     * Gets the value of the monitoredAttributeName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getMonitoredAttributeName() {
        return monitoredAttributeName;
    }

    /**
     * Sets the value of the monitoredAttributeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setMonitoredAttributeName(JAXBElement<String> value) {
        this.monitoredAttributeName = value;
    }

    /**
     * Gets the value of the pollingInterval property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPollingInterval() {
        return pollingInterval;
    }

    /**
     * Sets the value of the pollingInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPollingInterval(Integer value) {
        this.pollingInterval = value;
    }

}
