//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.17 at 03:40:53 PM CET 
//


package it.senape.wldiag.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Corresponds to SNMPGaugeMonitorMBean
 *  (Interface=weblogic.management.configuration.SNMPGaugeMonitorMBean)
 * 
 * <p>Java class for snmp-gauge-monitorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="snmp-gauge-monitorType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://xmlns.oracle.com/weblogic/domain}snmp-jmx-monitorType">
 *       &lt;sequence>
 *         &lt;element name="threshold-high" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="threshold-low" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "snmp-gauge-monitorType", propOrder = {
    "thresholdHigh",
    "thresholdLow"
})
public class SnmpGaugeMonitorType
    extends SnmpJmxMonitorType
{

    @XmlElement(name = "threshold-high")
    protected Integer thresholdHigh;
    @XmlElement(name = "threshold-low")
    protected Integer thresholdLow;

    /**
     * Gets the value of the thresholdHigh property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getThresholdHigh() {
        return thresholdHigh;
    }

    /**
     * Sets the value of the thresholdHigh property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setThresholdHigh(Integer value) {
        this.thresholdHigh = value;
    }

    /**
     * Gets the value of the thresholdLow property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getThresholdLow() {
        return thresholdLow;
    }

    /**
     * Sets the value of the thresholdLow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setThresholdLow(Integer value) {
        this.thresholdLow = value;
    }

}
