//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.17 at 03:40:53 PM CET 
//


package it.senape.wldiag.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * Corresponds to UserLockoutManagerMBean
 *  (Interface=weblogic.management.security.authentication.UserLockoutManagerMBean)
 * 
 * <p>Java class for user-lockout-managerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="user-lockout-managerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lockout-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="lockout-threshold" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="lockout-duration" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="lockout-reset-duration" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="lockout-cache-size" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="lockout-gc-threshold" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="compatibility-object-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "user-lockout-managerType", namespace = "http://xmlns.oracle.com/weblogic/security", propOrder = {
    "lockoutEnabled",
    "lockoutThreshold",
    "lockoutDuration",
    "lockoutResetDuration",
    "lockoutCacheSize",
    "lockoutGcThreshold",
    "name",
    "compatibilityObjectName"
})
public class UserLockoutManagerType {

    @XmlElement(name = "lockout-enabled", defaultValue = "true")
    protected Boolean lockoutEnabled;
    @XmlElement(name = "lockout-threshold", defaultValue = "5")
    protected Integer lockoutThreshold;
    @XmlElement(name = "lockout-duration", defaultValue = "30")
    protected Integer lockoutDuration;
    @XmlElement(name = "lockout-reset-duration", defaultValue = "5")
    protected Integer lockoutResetDuration;
    @XmlElement(name = "lockout-cache-size", defaultValue = "5")
    protected Integer lockoutCacheSize;
    @XmlElement(name = "lockout-gc-threshold", defaultValue = "400")
    protected Integer lockoutGcThreshold;
    @XmlElementRef(name = "name", namespace = "http://xmlns.oracle.com/weblogic/security", type = JAXBElement.class, required = false)
    protected JAXBElement<String> name;
    @XmlElementRef(name = "compatibility-object-name", namespace = "http://xmlns.oracle.com/weblogic/security", type = JAXBElement.class, required = false)
    protected JAXBElement<String> compatibilityObjectName;

    /**
     * Gets the value of the lockoutEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLockoutEnabled() {
        return lockoutEnabled;
    }

    /**
     * Sets the value of the lockoutEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLockoutEnabled(Boolean value) {
        this.lockoutEnabled = value;
    }

    /**
     * Gets the value of the lockoutThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLockoutThreshold() {
        return lockoutThreshold;
    }

    /**
     * Sets the value of the lockoutThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLockoutThreshold(Integer value) {
        this.lockoutThreshold = value;
    }

    /**
     * Gets the value of the lockoutDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLockoutDuration() {
        return lockoutDuration;
    }

    /**
     * Sets the value of the lockoutDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLockoutDuration(Integer value) {
        this.lockoutDuration = value;
    }

    /**
     * Gets the value of the lockoutResetDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLockoutResetDuration() {
        return lockoutResetDuration;
    }

    /**
     * Sets the value of the lockoutResetDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLockoutResetDuration(Integer value) {
        this.lockoutResetDuration = value;
    }

    /**
     * Gets the value of the lockoutCacheSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLockoutCacheSize() {
        return lockoutCacheSize;
    }

    /**
     * Sets the value of the lockoutCacheSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLockoutCacheSize(Integer value) {
        this.lockoutCacheSize = value;
    }

    /**
     * Gets the value of the lockoutGcThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLockoutGcThreshold() {
        return lockoutGcThreshold;
    }

    /**
     * Sets the value of the lockoutGcThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLockoutGcThreshold(Integer value) {
        this.lockoutGcThreshold = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setName(JAXBElement<String> value) {
        this.name = value;
    }

    /**
     * Gets the value of the compatibilityObjectName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCompatibilityObjectName() {
        return compatibilityObjectName;
    }

    /**
     * Sets the value of the compatibilityObjectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCompatibilityObjectName(JAXBElement<String> value) {
        this.compatibilityObjectName = value;
    }

}
