//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.17 at 03:40:53 PM CET 
//


package it.senape.wldiag.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * Corresponds to WebAppContainerMBean
 *  (Interface=weblogic.management.configuration.WebAppContainerMBean)
 * 
 * <p>Java class for web-app-containerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="web-app-containerType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://xmlns.oracle.com/weblogic/domain}configurationType">
 *       &lt;sequence>
 *         &lt;element name="relogin-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="allow-all-roles" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="filter-dispatched-requests-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="overload-protection-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="x-powered-by-header-level" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="NONE"/>
 *               &lt;enumeration value="SHORT"/>
 *               &lt;enumeration value="MEDIUM"/>
 *               &lt;enumeration value="FULL"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="mime-mapping-file" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="optimistic-serialization" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="retain-original-url" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="servlet-authentication-form-url" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="rtexprvalue-jsp-param-name" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="client-cert-proxy-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="http-trace-support-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="weblogic-plugin-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="auth-cookie-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="wap-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="post-timeout-secs" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="120"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="max-post-time-secs" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="max-post-size" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="work-context-propagation-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="p3p-header-value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="jsp-compiler-backwards-compatible" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="servlet-reload-check-secs" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="show-archived-real-path-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "web-app-containerType", propOrder = {
    "reloginEnabled",
    "allowAllRoles",
    "filterDispatchedRequestsEnabled",
    "overloadProtectionEnabled",
    "xPoweredByHeaderLevel",
    "mimeMappingFile",
    "optimisticSerialization",
    "retainOriginalUrl",
    "servletAuthenticationFormUrl",
    "rtexprvalueJspParamName",
    "clientCertProxyEnabled",
    "httpTraceSupportEnabled",
    "weblogicPluginEnabled",
    "authCookieEnabled",
    "wapEnabled",
    "postTimeoutSecs",
    "maxPostTimeSecs",
    "maxPostSize",
    "workContextPropagationEnabled",
    "p3PHeaderValue",
    "jspCompilerBackwardsCompatible",
    "servletReloadCheckSecs",
    "showArchivedRealPathEnabled"
})
public class WebAppContainerType
    extends ConfigurationType
{

    @XmlElement(name = "relogin-enabled", defaultValue = "false")
    protected Boolean reloginEnabled;
    @XmlElement(name = "allow-all-roles", defaultValue = "false")
    protected Boolean allowAllRoles;
    @XmlElement(name = "filter-dispatched-requests-enabled", defaultValue = "false")
    protected Boolean filterDispatchedRequestsEnabled;
    @XmlElement(name = "overload-protection-enabled", defaultValue = "false")
    protected Boolean overloadProtectionEnabled;
    @XmlElementRef(name = "x-powered-by-header-level", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> xPoweredByHeaderLevel;
    @XmlElementRef(name = "mime-mapping-file", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> mimeMappingFile;
    @XmlElement(name = "optimistic-serialization", defaultValue = "false")
    protected Boolean optimisticSerialization;
    @XmlElement(name = "retain-original-url", defaultValue = "false")
    protected Boolean retainOriginalUrl;
    @XmlElement(name = "servlet-authentication-form-url", defaultValue = "true")
    protected Boolean servletAuthenticationFormUrl;
    @XmlElement(name = "rtexprvalue-jsp-param-name", defaultValue = "false")
    protected Boolean rtexprvalueJspParamName;
    @XmlElement(name = "client-cert-proxy-enabled", defaultValue = "false")
    protected Boolean clientCertProxyEnabled;
    @XmlElement(name = "http-trace-support-enabled", defaultValue = "false")
    protected Boolean httpTraceSupportEnabled;
    @XmlElement(name = "weblogic-plugin-enabled", defaultValue = "false")
    protected Boolean weblogicPluginEnabled;
    @XmlElement(name = "auth-cookie-enabled", defaultValue = "true")
    protected Boolean authCookieEnabled;
    @XmlElement(name = "wap-enabled", defaultValue = "false")
    protected Boolean wapEnabled;
    @XmlElement(name = "post-timeout-secs", defaultValue = "30")
    protected Integer postTimeoutSecs;
    @XmlElement(name = "max-post-time-secs", defaultValue = "-1")
    protected Integer maxPostTimeSecs;
    @XmlElement(name = "max-post-size", defaultValue = "-1")
    protected Integer maxPostSize;
    @XmlElement(name = "work-context-propagation-enabled", defaultValue = "true")
    protected Boolean workContextPropagationEnabled;
    @XmlElementRef(name = "p3p-header-value", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> p3PHeaderValue;
    @XmlElement(name = "jsp-compiler-backwards-compatible", defaultValue = "false")
    protected Boolean jspCompilerBackwardsCompatible;
    @XmlElement(name = "servlet-reload-check-secs", defaultValue = "1")
    protected Integer servletReloadCheckSecs;
    @XmlElement(name = "show-archived-real-path-enabled", defaultValue = "false")
    protected Boolean showArchivedRealPathEnabled;

    /**
     * Gets the value of the reloginEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReloginEnabled() {
        return reloginEnabled;
    }

    /**
     * Sets the value of the reloginEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReloginEnabled(Boolean value) {
        this.reloginEnabled = value;
    }

    /**
     * Gets the value of the allowAllRoles property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowAllRoles() {
        return allowAllRoles;
    }

    /**
     * Sets the value of the allowAllRoles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowAllRoles(Boolean value) {
        this.allowAllRoles = value;
    }

    /**
     * Gets the value of the filterDispatchedRequestsEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFilterDispatchedRequestsEnabled() {
        return filterDispatchedRequestsEnabled;
    }

    /**
     * Sets the value of the filterDispatchedRequestsEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFilterDispatchedRequestsEnabled(Boolean value) {
        this.filterDispatchedRequestsEnabled = value;
    }

    /**
     * Gets the value of the overloadProtectionEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOverloadProtectionEnabled() {
        return overloadProtectionEnabled;
    }

    /**
     * Sets the value of the overloadProtectionEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOverloadProtectionEnabled(Boolean value) {
        this.overloadProtectionEnabled = value;
    }

    /**
     * Gets the value of the xPoweredByHeaderLevel property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getXPoweredByHeaderLevel() {
        return xPoweredByHeaderLevel;
    }

    /**
     * Sets the value of the xPoweredByHeaderLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setXPoweredByHeaderLevel(JAXBElement<String> value) {
        this.xPoweredByHeaderLevel = value;
    }

    /**
     * Gets the value of the mimeMappingFile property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getMimeMappingFile() {
        return mimeMappingFile;
    }

    /**
     * Sets the value of the mimeMappingFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setMimeMappingFile(JAXBElement<String> value) {
        this.mimeMappingFile = value;
    }

    /**
     * Gets the value of the optimisticSerialization property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOptimisticSerialization() {
        return optimisticSerialization;
    }

    /**
     * Sets the value of the optimisticSerialization property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOptimisticSerialization(Boolean value) {
        this.optimisticSerialization = value;
    }

    /**
     * Gets the value of the retainOriginalUrl property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRetainOriginalUrl() {
        return retainOriginalUrl;
    }

    /**
     * Sets the value of the retainOriginalUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRetainOriginalUrl(Boolean value) {
        this.retainOriginalUrl = value;
    }

    /**
     * Gets the value of the servletAuthenticationFormUrl property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isServletAuthenticationFormUrl() {
        return servletAuthenticationFormUrl;
    }

    /**
     * Sets the value of the servletAuthenticationFormUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setServletAuthenticationFormUrl(Boolean value) {
        this.servletAuthenticationFormUrl = value;
    }

    /**
     * Gets the value of the rtexprvalueJspParamName property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRtexprvalueJspParamName() {
        return rtexprvalueJspParamName;
    }

    /**
     * Sets the value of the rtexprvalueJspParamName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRtexprvalueJspParamName(Boolean value) {
        this.rtexprvalueJspParamName = value;
    }

    /**
     * Gets the value of the clientCertProxyEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isClientCertProxyEnabled() {
        return clientCertProxyEnabled;
    }

    /**
     * Sets the value of the clientCertProxyEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setClientCertProxyEnabled(Boolean value) {
        this.clientCertProxyEnabled = value;
    }

    /**
     * Gets the value of the httpTraceSupportEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHttpTraceSupportEnabled() {
        return httpTraceSupportEnabled;
    }

    /**
     * Sets the value of the httpTraceSupportEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHttpTraceSupportEnabled(Boolean value) {
        this.httpTraceSupportEnabled = value;
    }

    /**
     * Gets the value of the weblogicPluginEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWeblogicPluginEnabled() {
        return weblogicPluginEnabled;
    }

    /**
     * Sets the value of the weblogicPluginEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWeblogicPluginEnabled(Boolean value) {
        this.weblogicPluginEnabled = value;
    }

    /**
     * Gets the value of the authCookieEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAuthCookieEnabled() {
        return authCookieEnabled;
    }

    /**
     * Sets the value of the authCookieEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAuthCookieEnabled(Boolean value) {
        this.authCookieEnabled = value;
    }

    /**
     * Gets the value of the wapEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWapEnabled() {
        return wapEnabled;
    }

    /**
     * Sets the value of the wapEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWapEnabled(Boolean value) {
        this.wapEnabled = value;
    }

    /**
     * Gets the value of the postTimeoutSecs property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPostTimeoutSecs() {
        return postTimeoutSecs;
    }

    /**
     * Sets the value of the postTimeoutSecs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPostTimeoutSecs(Integer value) {
        this.postTimeoutSecs = value;
    }

    /**
     * Gets the value of the maxPostTimeSecs property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxPostTimeSecs() {
        return maxPostTimeSecs;
    }

    /**
     * Sets the value of the maxPostTimeSecs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxPostTimeSecs(Integer value) {
        this.maxPostTimeSecs = value;
    }

    /**
     * Gets the value of the maxPostSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxPostSize() {
        return maxPostSize;
    }

    /**
     * Sets the value of the maxPostSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxPostSize(Integer value) {
        this.maxPostSize = value;
    }

    /**
     * Gets the value of the workContextPropagationEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWorkContextPropagationEnabled() {
        return workContextPropagationEnabled;
    }

    /**
     * Sets the value of the workContextPropagationEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWorkContextPropagationEnabled(Boolean value) {
        this.workContextPropagationEnabled = value;
    }

    /**
     * Gets the value of the p3PHeaderValue property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getP3PHeaderValue() {
        return p3PHeaderValue;
    }

    /**
     * Sets the value of the p3PHeaderValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setP3PHeaderValue(JAXBElement<String> value) {
        this.p3PHeaderValue = value;
    }

    /**
     * Gets the value of the jspCompilerBackwardsCompatible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isJspCompilerBackwardsCompatible() {
        return jspCompilerBackwardsCompatible;
    }

    /**
     * Sets the value of the jspCompilerBackwardsCompatible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setJspCompilerBackwardsCompatible(Boolean value) {
        this.jspCompilerBackwardsCompatible = value;
    }

    /**
     * Gets the value of the servletReloadCheckSecs property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getServletReloadCheckSecs() {
        return servletReloadCheckSecs;
    }

    /**
     * Sets the value of the servletReloadCheckSecs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setServletReloadCheckSecs(Integer value) {
        this.servletReloadCheckSecs = value;
    }

    /**
     * Gets the value of the showArchivedRealPathEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowArchivedRealPathEnabled() {
        return showArchivedRealPathEnabled;
    }

    /**
     * Sets the value of the showArchivedRealPathEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowArchivedRealPathEnabled(Boolean value) {
        this.showArchivedRealPathEnabled = value;
    }

}
