//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.17 at 03:40:53 PM CET 
//


package it.senape.wldiag.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * Corresponds to WebServerLogMBean
 *  (Interface=weblogic.management.configuration.WebServerLogMBean)
 * 
 * <p>Java class for web-server-logType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="web-server-logType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://xmlns.oracle.com/weblogic/domain}log-fileType">
 *       &lt;sequence>
 *         &lt;element name="logging-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="elf-fields" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="log-file-format" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="common"/>
 *               &lt;enumeration value="extended"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="log-time-in-gmt" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="log-milli-seconds" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "web-server-logType", propOrder = {
    "loggingEnabled",
    "elfFields",
    "logFileFormat",
    "logTimeInGmt",
    "logMilliSeconds"
})
public class WebServerLogType
    extends LogFileType
{

    @XmlElement(name = "logging-enabled", defaultValue = "true")
    protected Boolean loggingEnabled;
    @XmlElementRef(name = "elf-fields", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> elfFields;
    @XmlElementRef(name = "log-file-format", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> logFileFormat;
    @XmlElement(name = "log-time-in-gmt", defaultValue = "false")
    protected Boolean logTimeInGmt;
    @XmlElement(name = "log-milli-seconds", defaultValue = "false")
    protected Boolean logMilliSeconds;

    /**
     * Gets the value of the loggingEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLoggingEnabled() {
        return loggingEnabled;
    }

    /**
     * Sets the value of the loggingEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLoggingEnabled(Boolean value) {
        this.loggingEnabled = value;
    }

    /**
     * Gets the value of the elfFields property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getElfFields() {
        return elfFields;
    }

    /**
     * Sets the value of the elfFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setElfFields(JAXBElement<String> value) {
        this.elfFields = value;
    }

    /**
     * Gets the value of the logFileFormat property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLogFileFormat() {
        return logFileFormat;
    }

    /**
     * Sets the value of the logFileFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLogFileFormat(JAXBElement<String> value) {
        this.logFileFormat = value;
    }

    /**
     * Gets the value of the logTimeInGmt property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLogTimeInGmt() {
        return logTimeInGmt;
    }

    /**
     * Sets the value of the logTimeInGmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLogTimeInGmt(Boolean value) {
        this.logTimeInGmt = value;
    }

    /**
     * Gets the value of the logMilliSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLogMilliSeconds() {
        return logMilliSeconds;
    }

    /**
     * Sets the value of the logMilliSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLogMilliSeconds(Boolean value) {
        this.logMilliSeconds = value;
    }

}
