//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.17 at 03:40:53 PM CET 
//


package it.senape.wldiag.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * Corresponds to WLDFServerDiagnosticMBean
 *  (Interface=weblogic.management.configuration.WLDFServerDiagnosticMBean)
 * 
 * <p>Java class for wldf-server-diagnosticType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wldf-server-diagnosticType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://xmlns.oracle.com/weblogic/domain}configurationType">
 *       &lt;sequence>
 *         &lt;element name="image-dir" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="image-timeout" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="1440"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="events-image-capture-interval" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="diagnostic-store-dir" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="diagnostic-store-file-locking-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="diagnostic-data-archive-type" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="FileStoreArchive"/>
 *               &lt;enumeration value="JDBCArchive"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="diagnostic-jdbc-resource" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="synchronous-event-persistence-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="event-persistence-interval" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="diagnostic-context-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="data-retirement-test-mode-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="data-retirement-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="preferred-store-size-limit" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="store-size-check-period" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="wldf-data-retirement-by-age" type="{http://xmlns.oracle.com/weblogic/domain}wldf-data-retirement-by-ageType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="wldf-diagnostic-volume" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Off"/>
 *               &lt;enumeration value="Low"/>
 *               &lt;enumeration value="Medium"/>
 *               &lt;enumeration value="High"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wldf-server-diagnosticType", propOrder = {
    "imageDir",
    "imageTimeout",
    "eventsImageCaptureInterval",
    "diagnosticStoreDir",
    "diagnosticStoreFileLockingEnabled",
    "diagnosticDataArchiveType",
    "diagnosticJdbcResource",
    "synchronousEventPersistenceEnabled",
    "eventPersistenceInterval",
    "diagnosticContextEnabled",
    "dataRetirementTestModeEnabled",
    "dataRetirementEnabled",
    "preferredStoreSizeLimit",
    "storeSizeCheckPeriod",
    "wldfDataRetirementByAge",
    "wldfDiagnosticVolume"
})
public class WldfServerDiagnosticType
    extends ConfigurationType
{

    @XmlElementRef(name = "image-dir", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> imageDir;
    @XmlElement(name = "image-timeout", defaultValue = "1")
    protected Integer imageTimeout;
    @XmlElement(name = "events-image-capture-interval", defaultValue = "60000")
    protected Long eventsImageCaptureInterval;
    @XmlElementRef(name = "diagnostic-store-dir", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> diagnosticStoreDir;
    @XmlElement(name = "diagnostic-store-file-locking-enabled", defaultValue = "true")
    protected Boolean diagnosticStoreFileLockingEnabled;
    @XmlElementRef(name = "diagnostic-data-archive-type", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> diagnosticDataArchiveType;
    @XmlElementRef(name = "diagnostic-jdbc-resource", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> diagnosticJdbcResource;
    @XmlElement(name = "synchronous-event-persistence-enabled", defaultValue = "false")
    protected Boolean synchronousEventPersistenceEnabled;
    @XmlElement(name = "event-persistence-interval", defaultValue = "5000")
    protected Long eventPersistenceInterval;
    @XmlElement(name = "diagnostic-context-enabled", defaultValue = "false")
    protected Boolean diagnosticContextEnabled;
    @XmlElement(name = "data-retirement-test-mode-enabled")
    protected Boolean dataRetirementTestModeEnabled;
    @XmlElement(name = "data-retirement-enabled", defaultValue = "true")
    protected Boolean dataRetirementEnabled;
    @XmlElement(name = "preferred-store-size-limit", defaultValue = "100")
    protected Integer preferredStoreSizeLimit;
    @XmlElement(name = "store-size-check-period", defaultValue = "1")
    protected Integer storeSizeCheckPeriod;
    @XmlElement(name = "wldf-data-retirement-by-age", nillable = true)
    protected List<WldfDataRetirementByAgeType> wldfDataRetirementByAge;
    @XmlElementRef(name = "wldf-diagnostic-volume", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> wldfDiagnosticVolume;

    /**
     * Gets the value of the imageDir property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getImageDir() {
        return imageDir;
    }

    /**
     * Sets the value of the imageDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setImageDir(JAXBElement<String> value) {
        this.imageDir = value;
    }

    /**
     * Gets the value of the imageTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getImageTimeout() {
        return imageTimeout;
    }

    /**
     * Sets the value of the imageTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setImageTimeout(Integer value) {
        this.imageTimeout = value;
    }

    /**
     * Gets the value of the eventsImageCaptureInterval property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getEventsImageCaptureInterval() {
        return eventsImageCaptureInterval;
    }

    /**
     * Sets the value of the eventsImageCaptureInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setEventsImageCaptureInterval(Long value) {
        this.eventsImageCaptureInterval = value;
    }

    /**
     * Gets the value of the diagnosticStoreDir property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDiagnosticStoreDir() {
        return diagnosticStoreDir;
    }

    /**
     * Sets the value of the diagnosticStoreDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDiagnosticStoreDir(JAXBElement<String> value) {
        this.diagnosticStoreDir = value;
    }

    /**
     * Gets the value of the diagnosticStoreFileLockingEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDiagnosticStoreFileLockingEnabled() {
        return diagnosticStoreFileLockingEnabled;
    }

    /**
     * Sets the value of the diagnosticStoreFileLockingEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDiagnosticStoreFileLockingEnabled(Boolean value) {
        this.diagnosticStoreFileLockingEnabled = value;
    }

    /**
     * Gets the value of the diagnosticDataArchiveType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDiagnosticDataArchiveType() {
        return diagnosticDataArchiveType;
    }

    /**
     * Sets the value of the diagnosticDataArchiveType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDiagnosticDataArchiveType(JAXBElement<String> value) {
        this.diagnosticDataArchiveType = value;
    }

    /**
     * Gets the value of the diagnosticJdbcResource property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDiagnosticJdbcResource() {
        return diagnosticJdbcResource;
    }

    /**
     * Sets the value of the diagnosticJdbcResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDiagnosticJdbcResource(JAXBElement<String> value) {
        this.diagnosticJdbcResource = value;
    }

    /**
     * Gets the value of the synchronousEventPersistenceEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSynchronousEventPersistenceEnabled() {
        return synchronousEventPersistenceEnabled;
    }

    /**
     * Sets the value of the synchronousEventPersistenceEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSynchronousEventPersistenceEnabled(Boolean value) {
        this.synchronousEventPersistenceEnabled = value;
    }

    /**
     * Gets the value of the eventPersistenceInterval property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getEventPersistenceInterval() {
        return eventPersistenceInterval;
    }

    /**
     * Sets the value of the eventPersistenceInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setEventPersistenceInterval(Long value) {
        this.eventPersistenceInterval = value;
    }

    /**
     * Gets the value of the diagnosticContextEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDiagnosticContextEnabled() {
        return diagnosticContextEnabled;
    }

    /**
     * Sets the value of the diagnosticContextEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDiagnosticContextEnabled(Boolean value) {
        this.diagnosticContextEnabled = value;
    }

    /**
     * Gets the value of the dataRetirementTestModeEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDataRetirementTestModeEnabled() {
        return dataRetirementTestModeEnabled;
    }

    /**
     * Sets the value of the dataRetirementTestModeEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDataRetirementTestModeEnabled(Boolean value) {
        this.dataRetirementTestModeEnabled = value;
    }

    /**
     * Gets the value of the dataRetirementEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDataRetirementEnabled() {
        return dataRetirementEnabled;
    }

    /**
     * Sets the value of the dataRetirementEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDataRetirementEnabled(Boolean value) {
        this.dataRetirementEnabled = value;
    }

    /**
     * Gets the value of the preferredStoreSizeLimit property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPreferredStoreSizeLimit() {
        return preferredStoreSizeLimit;
    }

    /**
     * Sets the value of the preferredStoreSizeLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPreferredStoreSizeLimit(Integer value) {
        this.preferredStoreSizeLimit = value;
    }

    /**
     * Gets the value of the storeSizeCheckPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStoreSizeCheckPeriod() {
        return storeSizeCheckPeriod;
    }

    /**
     * Sets the value of the storeSizeCheckPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStoreSizeCheckPeriod(Integer value) {
        this.storeSizeCheckPeriod = value;
    }

    /**
     * Gets the value of the wldfDataRetirementByAge property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wldfDataRetirementByAge property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWldfDataRetirementByAge().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WldfDataRetirementByAgeType }
     * 
     * 
     */
    public List<WldfDataRetirementByAgeType> getWldfDataRetirementByAge() {
        if (wldfDataRetirementByAge == null) {
            wldfDataRetirementByAge = new ArrayList<WldfDataRetirementByAgeType>();
        }
        return this.wldfDataRetirementByAge;
    }

    /**
     * Gets the value of the wldfDiagnosticVolume property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getWldfDiagnosticVolume() {
        return wldfDiagnosticVolume;
    }

    /**
     * Sets the value of the wldfDiagnosticVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setWldfDiagnosticVolume(JAXBElement<String> value) {
        this.wldfDiagnosticVolume = value;
    }

}
