//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.17 at 03:40:53 PM CET 
//


package it.senape.wldiag.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Corresponds to WLDFDataRetirementByAgeMBean
 *  (Interface=weblogic.management.configuration.WLDFDataRetirementByAgeMBean)
 * 
 * <p>Java class for wldf-data-retirement-by-ageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wldf-data-retirement-by-ageType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://xmlns.oracle.com/weblogic/domain}wldf-data-retirementType">
 *       &lt;sequence>
 *         &lt;element name="retirement-age" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wldf-data-retirement-by-ageType", propOrder = {
    "retirementAge"
})
public class WldfDataRetirementByAgeType
    extends WldfDataRetirementType
{

    @XmlElement(name = "retirement-age", defaultValue = "72")
    protected Integer retirementAge;

    /**
     * Gets the value of the retirementAge property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRetirementAge() {
        return retirementAge;
    }

    /**
     * Sets the value of the retirementAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRetirementAge(Integer value) {
        this.retirementAge = value;
    }

}
