//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.17 at 03:40:53 PM CET 
//


package it.senape.wldiag.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * Corresponds to WTCRemoteTuxDomMBean
 *  (Interface=weblogic.management.configuration.WTCRemoteTuxDomMBean)
 * 
 * <p>Java class for wtc-remote-tux-domType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wtc-remote-tux-domType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://xmlns.oracle.com/weblogic/domain}configurationType">
 *       &lt;sequence>
 *         &lt;element name="access-point" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="access-point-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="connection-policy" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="ON_DEMAND"/>
 *               &lt;enumeration value="ON_STARTUP"/>
 *               &lt;enumeration value="INCOMING_ONLY"/>
 *               &lt;enumeration value="LOCAL"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="acl-policy" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="GLOBAL"/>
 *               &lt;enumeration value="LOCAL"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="credential-policy" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="GLOBAL"/>
 *               &lt;enumeration value="LOCAL"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tp-usr-file" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="local-access-point" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="conn-principal-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="retry-interval" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *               &lt;minInclusive value="-1"/>
 *               &lt;maxInclusive value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="max-retries" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *               &lt;minInclusive value="-1"/>
 *               &lt;maxInclusive value="9223372036854775807"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nw-addr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="federation-url" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="federation-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cmp-limit" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="min-encrypt-bits" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="40"/>
 *               &lt;enumeration value="56"/>
 *               &lt;enumeration value="128"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="max-encrypt-bits" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="40"/>
 *               &lt;enumeration value="56"/>
 *               &lt;enumeration value="128"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="app-key" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="TpUsrFile"/>
 *               &lt;enumeration value="LDAP"/>
 *               &lt;enumeration value="Custom"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="allow-anonymous" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="default-app-key" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="tuxedo-uid-kw" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tuxedo-gid-kw" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom-app-key-class" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom-app-key-class-param" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="keep-alive" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="-1"/>
 *               &lt;maxInclusive value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="keep-alive-wait" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wtc-remote-tux-domType", propOrder = {
    "accessPoint",
    "accessPointId",
    "connectionPolicy",
    "aclPolicy",
    "credentialPolicy",
    "tpUsrFile",
    "localAccessPoint",
    "connPrincipalName",
    "retryInterval",
    "maxRetries",
    "nwAddr",
    "federationUrl",
    "federationName",
    "cmpLimit",
    "minEncryptBits",
    "maxEncryptBits",
    "appKey",
    "allowAnonymous",
    "defaultAppKey",
    "tuxedoUidKw",
    "tuxedoGidKw",
    "customAppKeyClass",
    "customAppKeyClassParam",
    "keepAlive",
    "keepAliveWait"
})
public class WtcRemoteTuxDomType
    extends ConfigurationType
{

    @XmlElement(name = "access-point", defaultValue = "myRAP")
    protected String accessPoint;
    @XmlElement(name = "access-point-id", defaultValue = "myRAPId")
    protected String accessPointId;
    @XmlElementRef(name = "connection-policy", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> connectionPolicy;
    @XmlElementRef(name = "acl-policy", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> aclPolicy;
    @XmlElementRef(name = "credential-policy", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> credentialPolicy;
    @XmlElementRef(name = "tp-usr-file", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> tpUsrFile;
    @XmlElement(name = "local-access-point", defaultValue = "myLAP")
    protected String localAccessPoint;
    @XmlElementRef(name = "conn-principal-name", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> connPrincipalName;
    @XmlElement(name = "retry-interval", defaultValue = "-1")
    protected Integer retryInterval;
    @XmlElement(name = "max-retries", defaultValue = "-1")
    protected Long maxRetries;
    @XmlElementRef(name = "nw-addr", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> nwAddr;
    @XmlElementRef(name = "federation-url", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> federationUrl;
    @XmlElementRef(name = "federation-name", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> federationName;
    @XmlElement(name = "cmp-limit", defaultValue = "2147483647")
    protected Integer cmpLimit;
    @XmlElementRef(name = "min-encrypt-bits", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> minEncryptBits;
    @XmlElementRef(name = "max-encrypt-bits", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> maxEncryptBits;
    @XmlElementRef(name = "app-key", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> appKey;
    @XmlElement(name = "allow-anonymous", defaultValue = "false")
    protected Boolean allowAnonymous;
    @XmlElement(name = "default-app-key", defaultValue = "-1")
    protected Integer defaultAppKey;
    @XmlElementRef(name = "tuxedo-uid-kw", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> tuxedoUidKw;
    @XmlElementRef(name = "tuxedo-gid-kw", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> tuxedoGidKw;
    @XmlElementRef(name = "custom-app-key-class", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> customAppKeyClass;
    @XmlElementRef(name = "custom-app-key-class-param", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> customAppKeyClassParam;
    @XmlElement(name = "keep-alive", defaultValue = "0")
    protected Integer keepAlive;
    @XmlElement(name = "keep-alive-wait", defaultValue = "0")
    protected Integer keepAliveWait;

    /**
     * Gets the value of the accessPoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessPoint() {
        return accessPoint;
    }

    /**
     * Sets the value of the accessPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessPoint(String value) {
        this.accessPoint = value;
    }

    /**
     * Gets the value of the accessPointId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessPointId() {
        return accessPointId;
    }

    /**
     * Sets the value of the accessPointId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessPointId(String value) {
        this.accessPointId = value;
    }

    /**
     * Gets the value of the connectionPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getConnectionPolicy() {
        return connectionPolicy;
    }

    /**
     * Sets the value of the connectionPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setConnectionPolicy(JAXBElement<String> value) {
        this.connectionPolicy = value;
    }

    /**
     * Gets the value of the aclPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAclPolicy() {
        return aclPolicy;
    }

    /**
     * Sets the value of the aclPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAclPolicy(JAXBElement<String> value) {
        this.aclPolicy = value;
    }

    /**
     * Gets the value of the credentialPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCredentialPolicy() {
        return credentialPolicy;
    }

    /**
     * Sets the value of the credentialPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCredentialPolicy(JAXBElement<String> value) {
        this.credentialPolicy = value;
    }

    /**
     * Gets the value of the tpUsrFile property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTpUsrFile() {
        return tpUsrFile;
    }

    /**
     * Sets the value of the tpUsrFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTpUsrFile(JAXBElement<String> value) {
        this.tpUsrFile = value;
    }

    /**
     * Gets the value of the localAccessPoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalAccessPoint() {
        return localAccessPoint;
    }

    /**
     * Sets the value of the localAccessPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalAccessPoint(String value) {
        this.localAccessPoint = value;
    }

    /**
     * Gets the value of the connPrincipalName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getConnPrincipalName() {
        return connPrincipalName;
    }

    /**
     * Sets the value of the connPrincipalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setConnPrincipalName(JAXBElement<String> value) {
        this.connPrincipalName = value;
    }

    /**
     * Gets the value of the retryInterval property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRetryInterval() {
        return retryInterval;
    }

    /**
     * Sets the value of the retryInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRetryInterval(Integer value) {
        this.retryInterval = value;
    }

    /**
     * Gets the value of the maxRetries property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxRetries() {
        return maxRetries;
    }

    /**
     * Sets the value of the maxRetries property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxRetries(Long value) {
        this.maxRetries = value;
    }

    /**
     * Gets the value of the nwAddr property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getNwAddr() {
        return nwAddr;
    }

    /**
     * Sets the value of the nwAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setNwAddr(JAXBElement<String> value) {
        this.nwAddr = value;
    }

    /**
     * Gets the value of the federationUrl property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getFederationUrl() {
        return federationUrl;
    }

    /**
     * Sets the value of the federationUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setFederationUrl(JAXBElement<String> value) {
        this.federationUrl = value;
    }

    /**
     * Gets the value of the federationName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getFederationName() {
        return federationName;
    }

    /**
     * Sets the value of the federationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setFederationName(JAXBElement<String> value) {
        this.federationName = value;
    }

    /**
     * Gets the value of the cmpLimit property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCmpLimit() {
        return cmpLimit;
    }

    /**
     * Sets the value of the cmpLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCmpLimit(Integer value) {
        this.cmpLimit = value;
    }

    /**
     * Gets the value of the minEncryptBits property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getMinEncryptBits() {
        return minEncryptBits;
    }

    /**
     * Sets the value of the minEncryptBits property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setMinEncryptBits(JAXBElement<String> value) {
        this.minEncryptBits = value;
    }

    /**
     * Gets the value of the maxEncryptBits property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getMaxEncryptBits() {
        return maxEncryptBits;
    }

    /**
     * Sets the value of the maxEncryptBits property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setMaxEncryptBits(JAXBElement<String> value) {
        this.maxEncryptBits = value;
    }

    /**
     * Gets the value of the appKey property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAppKey() {
        return appKey;
    }

    /**
     * Sets the value of the appKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAppKey(JAXBElement<String> value) {
        this.appKey = value;
    }

    /**
     * Gets the value of the allowAnonymous property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowAnonymous() {
        return allowAnonymous;
    }

    /**
     * Sets the value of the allowAnonymous property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowAnonymous(Boolean value) {
        this.allowAnonymous = value;
    }

    /**
     * Gets the value of the defaultAppKey property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDefaultAppKey() {
        return defaultAppKey;
    }

    /**
     * Sets the value of the defaultAppKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDefaultAppKey(Integer value) {
        this.defaultAppKey = value;
    }

    /**
     * Gets the value of the tuxedoUidKw property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTuxedoUidKw() {
        return tuxedoUidKw;
    }

    /**
     * Sets the value of the tuxedoUidKw property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTuxedoUidKw(JAXBElement<String> value) {
        this.tuxedoUidKw = value;
    }

    /**
     * Gets the value of the tuxedoGidKw property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTuxedoGidKw() {
        return tuxedoGidKw;
    }

    /**
     * Sets the value of the tuxedoGidKw property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTuxedoGidKw(JAXBElement<String> value) {
        this.tuxedoGidKw = value;
    }

    /**
     * Gets the value of the customAppKeyClass property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCustomAppKeyClass() {
        return customAppKeyClass;
    }

    /**
     * Sets the value of the customAppKeyClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCustomAppKeyClass(JAXBElement<String> value) {
        this.customAppKeyClass = value;
    }

    /**
     * Gets the value of the customAppKeyClassParam property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCustomAppKeyClassParam() {
        return customAppKeyClassParam;
    }

    /**
     * Sets the value of the customAppKeyClassParam property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCustomAppKeyClassParam(JAXBElement<String> value) {
        this.customAppKeyClassParam = value;
    }

    /**
     * Gets the value of the keepAlive property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getKeepAlive() {
        return keepAlive;
    }

    /**
     * Sets the value of the keepAlive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setKeepAlive(Integer value) {
        this.keepAlive = value;
    }

    /**
     * Gets the value of the keepAliveWait property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getKeepAliveWait() {
        return keepAliveWait;
    }

    /**
     * Sets the value of the keepAliveWait property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setKeepAliveWait(Integer value) {
        this.keepAliveWait = value;
    }

}
