//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.17 at 03:40:53 PM CET 
//


package it.senape.wldiag.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * Corresponds to WTCtBridgeGlobalMBean
 *  (Interface=weblogic.management.configuration.WTCtBridgeGlobalMBean)
 * 
 * <p>Java class for wtc-tbridge-globalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wtc-tbridge-globalType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://xmlns.oracle.com/weblogic/domain}configurationType">
 *       &lt;sequence>
 *         &lt;element name="transactional" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Yes"/>
 *               &lt;enumeration value="No"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="timeout" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="retries" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="retry-delay" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="wls-error-destination" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tux-error-queue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="delivery-mode-override" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="PERSIST"/>
 *               &lt;enumeration value="NONPERSIST"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="default-reply-delivery-mode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="PERSIST"/>
 *               &lt;enumeration value="NONPERSIST"/>
 *               &lt;enumeration value="DEFAULT"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="user-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="allow-non-standard-types" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Yes"/>
 *               &lt;enumeration value="No"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="jndi-factory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="jms-factory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tux-factory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="jms-to-tux-priority-map" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tux-to-jms-priority-map" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wtc-tbridge-globalType", propOrder = {
    "transactional",
    "timeout",
    "retries",
    "retryDelay",
    "wlsErrorDestination",
    "tuxErrorQueue",
    "deliveryModeOverride",
    "defaultReplyDeliveryMode",
    "userId",
    "allowNonStandardTypes",
    "jndiFactory",
    "jmsFactory",
    "tuxFactory",
    "jmsToTuxPriorityMap",
    "tuxToJmsPriorityMap"
})
public class WtcTbridgeGlobalType
    extends ConfigurationType
{

    @XmlElementRef(name = "transactional", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> transactional;
    @XmlElement(defaultValue = "60")
    protected Integer timeout;
    @XmlElement(defaultValue = "0")
    protected Integer retries;
    @XmlElement(name = "retry-delay", defaultValue = "10")
    protected Integer retryDelay;
    @XmlElementRef(name = "wls-error-destination", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> wlsErrorDestination;
    @XmlElementRef(name = "tux-error-queue", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> tuxErrorQueue;
    @XmlElementRef(name = "delivery-mode-override", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> deliveryModeOverride;
    @XmlElementRef(name = "default-reply-delivery-mode", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> defaultReplyDeliveryMode;
    @XmlElementRef(name = "user-id", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> userId;
    @XmlElementRef(name = "allow-non-standard-types", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> allowNonStandardTypes;
    @XmlElement(name = "jndi-factory", defaultValue = "weblogic.jndi.WLInitialContextFactory")
    protected String jndiFactory;
    @XmlElement(name = "jms-factory", defaultValue = "weblogic.jms.XAConnectionFactory")
    protected String jmsFactory;
    @XmlElement(name = "tux-factory", defaultValue = "tuxedo.services.TuxedoConnection")
    protected String tuxFactory;
    @XmlElementRef(name = "jms-to-tux-priority-map", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> jmsToTuxPriorityMap;
    @XmlElementRef(name = "tux-to-jms-priority-map", namespace = "http://xmlns.oracle.com/weblogic/domain", type = JAXBElement.class, required = false)
    protected JAXBElement<String> tuxToJmsPriorityMap;

    /**
     * Gets the value of the transactional property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTransactional() {
        return transactional;
    }

    /**
     * Sets the value of the transactional property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTransactional(JAXBElement<String> value) {
        this.transactional = value;
    }

    /**
     * Gets the value of the timeout property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTimeout() {
        return timeout;
    }

    /**
     * Sets the value of the timeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTimeout(Integer value) {
        this.timeout = value;
    }

    /**
     * Gets the value of the retries property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRetries() {
        return retries;
    }

    /**
     * Sets the value of the retries property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRetries(Integer value) {
        this.retries = value;
    }

    /**
     * Gets the value of the retryDelay property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRetryDelay() {
        return retryDelay;
    }

    /**
     * Sets the value of the retryDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRetryDelay(Integer value) {
        this.retryDelay = value;
    }

    /**
     * Gets the value of the wlsErrorDestination property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getWlsErrorDestination() {
        return wlsErrorDestination;
    }

    /**
     * Sets the value of the wlsErrorDestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setWlsErrorDestination(JAXBElement<String> value) {
        this.wlsErrorDestination = value;
    }

    /**
     * Gets the value of the tuxErrorQueue property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTuxErrorQueue() {
        return tuxErrorQueue;
    }

    /**
     * Sets the value of the tuxErrorQueue property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTuxErrorQueue(JAXBElement<String> value) {
        this.tuxErrorQueue = value;
    }

    /**
     * Gets the value of the deliveryModeOverride property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDeliveryModeOverride() {
        return deliveryModeOverride;
    }

    /**
     * Sets the value of the deliveryModeOverride property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDeliveryModeOverride(JAXBElement<String> value) {
        this.deliveryModeOverride = value;
    }

    /**
     * Gets the value of the defaultReplyDeliveryMode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDefaultReplyDeliveryMode() {
        return defaultReplyDeliveryMode;
    }

    /**
     * Sets the value of the defaultReplyDeliveryMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDefaultReplyDeliveryMode(JAXBElement<String> value) {
        this.defaultReplyDeliveryMode = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setUserId(JAXBElement<String> value) {
        this.userId = value;
    }

    /**
     * Gets the value of the allowNonStandardTypes property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAllowNonStandardTypes() {
        return allowNonStandardTypes;
    }

    /**
     * Sets the value of the allowNonStandardTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAllowNonStandardTypes(JAXBElement<String> value) {
        this.allowNonStandardTypes = value;
    }

    /**
     * Gets the value of the jndiFactory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJndiFactory() {
        return jndiFactory;
    }

    /**
     * Sets the value of the jndiFactory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJndiFactory(String value) {
        this.jndiFactory = value;
    }

    /**
     * Gets the value of the jmsFactory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJmsFactory() {
        return jmsFactory;
    }

    /**
     * Sets the value of the jmsFactory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJmsFactory(String value) {
        this.jmsFactory = value;
    }

    /**
     * Gets the value of the tuxFactory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTuxFactory() {
        return tuxFactory;
    }

    /**
     * Sets the value of the tuxFactory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTuxFactory(String value) {
        this.tuxFactory = value;
    }

    /**
     * Gets the value of the jmsToTuxPriorityMap property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getJmsToTuxPriorityMap() {
        return jmsToTuxPriorityMap;
    }

    /**
     * Sets the value of the jmsToTuxPriorityMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setJmsToTuxPriorityMap(JAXBElement<String> value) {
        this.jmsToTuxPriorityMap = value;
    }

    /**
     * Gets the value of the tuxToJmsPriorityMap property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTuxToJmsPriorityMap() {
        return tuxToJmsPriorityMap;
    }

    /**
     * Sets the value of the tuxToJmsPriorityMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTuxToJmsPriorityMap(JAXBElement<String> value) {
        this.tuxToJmsPriorityMap = value;
    }

}
