export class JdbcResource {
  private autoCommit: boolean; //false
  private enabled: boolean; //true
  private isXA: boolean; //false
  private isJTS: boolean; //false
  private vendorID: number; //100
  private connUsed: boolean; //false
  private doInit: boolean; //false
  private destroyed: boolean; //false
  private poolname: string; //EBOOKING_DATASOURCE
  private appname: string; //null
  private moduleName: string; //null
  private connectTime: number; //55
  private dirtyIsolationLevel: boolean; //false
  private initialIsolationLevel: number; //2
  private infected: boolean; //false
  private lastSuccessfulConnectionUse: number; //1516872070308
  private secondsToTrustAnIdlePoolConnection: number; //10
  private currentUser: string; //null
  private currentThread: string; //null
  private lastUser: string; //null
  private currentError: string; //null
  private currentErrorTimestamp: string; //null
  private JDBC4Runtime: boolean; //true
  private supportStatementPoolable: boolean; //true
  private needRestoreClientInfo: boolean; //false
  private defaultClientInfo: string; //{}
  private supportIsValid: boolean; //true
  private stackTrace: string;
}
